version: '3.8'

services:
  enhanced-mcp-server:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "8001:8001"
    environment:
      - JINA_API_KEY=${JINA_API_KEY}
      - GEMINI_API_KEY=${GEMINI_API_KEY}
      - DEEPL_API_KEY=${DEEPL_API_KEY}
      - REDIS_URL=${REDIS_URL}
      - LOG_LEVEL=INFO
      - WEB_HOST=0.0.0.0
      - WEB_PORT=8001
    volumes:
      - ./logs:/app/logs
    restart: unless-stopped
    healthcheck:
      test: ["CMD", "python", "-c", "import requests; requests.get('http://localhost:8001/health')"]
      interval: 30s
      timeout: 10s
      retries: 3
      start_period: 40s

  redis:
    image: redis:7-alpine
    ports:
      - "6379:6379"
    volumes:
      - redis_data:/data
    restart: unless-stopped
    command: redis-server --appendonly yes
    healthcheck:
      test: ["CMD", "redis-cli", "ping"]
      interval: 10s
      timeout: 3s
      retries: 3

volumes:
  redis_data: