      - name: Install dependencies
        run: |
          set -e
          pip install --upgrade pip
          # Install enhanced-mcp-server package in editable mode with dev dependencies
          pip install -e .[dev]

      - name: Lint (ruff)
        run: |
          ruff check . || (echo 'Run ruff --fix locally to address issues' && exit 1)

      - name: Run tests
        env:
          JINA_API_KEY: dummy_jina_key_12345
        run: |
          pytest

      - name: Build package
        run: |
          python -m build || echo 'Build optional'

      - name: Validate smithery.yaml exists
        run: |
          test -f smithery.yaml
